version: '3.5'
services:
  BMDBEMPLEADO:
    image: postgres:12
    volumes:
      - business-manager-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
  BMEMPLEADO:
    image: business-manager-empleado-server:1.0-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://BMDISCOVERY:8761/eureka
        -Dspring.profiles.active=docker
        -agentlib:jdwp=transport=dt_socket,address=5080,server=y,suspend=n
    restart: on-failure:10
    expose:
      - 8000
      - 5080
    ports:
      - 8000:8000
      - 5081:5081
    depends_on:
      - BMDBEMPLEADO
volumes:
  business-manager-data:
networks:
  default:
    external:
      name: BM_NETWORK
